version: '3.8'

services:
  tests-qa:
    build: .
    env_file:
      - config/.env.qa
    environment:
      - CI=true
    volumes:
      - ./reports-qa:/app/reports
      - ./allure-results-qa:/app/allure-results
    command: npx playwright test --project=chromium

  tests-stage:
    build: .
    env_file:
      - config/.env.stage
    environment:
      - CI=true
    volumes:
      - ./reports-stage:/app/reports
      - ./allure-results-stage:/app/allure-results
    command: npx playwright test --project=chromium --grep @smoke


